
name: Checkmarx AST Scan
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST GitHub Action
        uses: Checkmarx/ast-github-action@master
        with:
          project_name: ${{ github.repository }}
          base_uri: https://ast-master.dev.cxast.net/
          cx_tenant: organization
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --tags test1,test2 
