
name: Checkmarx AST Scan
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@v0.28
        with:
          project_name: ast-github-tester
          base_uri: https://ast-master.dev.cxast.net/
          cx_tenant: organization
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }} 
          additional_params: --scan-types sast --file-filter !readme --report-format sarif --output-name results
          

